[build]
  command = "yarn build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "Cache-Control" = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[headers]]
  for = "/output-*.css"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"




